# Generated by Django 5.0.2 on 2024-02-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drf',
            name='rating',
            field=models.IntegerField(choices=[(1, "1 - Shouldn't exist"), (2, '2 - Why does this exist'), (3, '3 - Mid'), (4, '4 - Makes sense'), (5, '5 - Peak')], default=3),
        ),
    ]
