# Generated by Django 5.0.2 on 2024-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_drf_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drf',
            name='rating',
            field=models.IntegerField(choices=[(1, "1 - Shouldn't exist"), (2, "2 - Doesn' make sense"), (3, '3 - Mid'), (4, '4 - Makes sense'), (5, '5 - Peak')], default=3),
        ),
    ]
